---
abstract: 'Slope One collaborative filtering for rated resources'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-SlopeOne
requires:
  Carp: 0
  Moo: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/Algorithm-SlopeOne/issues
  homepage: https://github.com/creaktive/Algorithm-SlopeOne
  repository: git://github.com/creaktive/Algorithm-SlopeOne.git
version: 0.002
